# Generated by Django 4.1.2 on 2022-11-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebDjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('genero', models.CharField(max_length=18)),
                ('duracion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('temporadas', models.IntegerField()),
                ('genero', models.CharField(max_length=23)),
            ],
        ),
        migrations.RenameModel(
            old_name='hoteles',
            new_name='music',
        ),
        migrations.DeleteModel(
            name='mascota',
        ),
        migrations.DeleteModel(
            name='vehiculos',
        ),
    ]
