# Generated by Django 4.1.2 on 2022-11-16 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebDjango', '0002_peliculas_serie_rename_hoteles_music_delete_mascota_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peliculas',
            old_name='duracion',
            new_name='duracion_en_minutos',
        ),
    ]
