# Generated by Django 4.1.2 on 2022-11-16 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebDjango', '0003_rename_duracion_peliculas_duracion_en_minutos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='cant_personas',
            new_name='duracion_de_la_cancion',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='ubicacion',
            new_name='genero',
        ),
    ]
