# Generated by Django 4.1.2 on 2022-11-16 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebDjango', '0005_rename_genero_music_cantante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='duracion_de_la_cancion',
            new_name='duracion_de_la_cancion_en_minutos',
        ),
    ]
